### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by xSke** [xSke/PluralKit#30]
* [x] System/member edit command rework (see #6)
* Better status information and prompting
  * [x] Member name conflict prompt (see #10)
* Better errors
  * Various hints
    * [ ] Hint "quoting names" on unresolved member name
    * [x] More specific help pages on unknown subcommand (instead of just ignoring)
  * [ ] Avatar size/format check (see #5)

(do comment with more suggestions!)
